const characters=['유기오','최오윤','강아지 보리','미래인','영원의 신천지','아기','미즈키','사이비','외할머니','도시'];
const themes=['고통','abortion','미래','생존권리','영원','존재','인식','해결','카오스','코스모스'];
const scenes=['호텔의 진동','붉은 우산','야마노테선','병원 복도','서점의 기억','강변의 미래인','지하 통로','호텔 로비의 거짓말','철도 건널목','병실 손잡이','폐쇄 승강장','다시 05:40'];
const materials=['철도 진동','붉은 우산','종이컵','문손잡이','전광판','바흐 선율','층간소음','차가운 피부','젖은 종이','백색광'];
const locations=['철도 전망 호텔','호텔 로비','병원 복도','야마노테선','철도 건널목','지하 통로','강변','서점','아파트','폐쇄 승강장'];
const times=['05:40','07:10','08:30','10:00','11:45','13:00','15:20','17:30','22:00','02:30'];
const situations=['진동 감지','우산 오인','병실 회피','기억 충돌','미래 기억','윤리 대화','동물 시점','사이비 설교','도시 과부하','부분 회수'];
const techniques=['의식의 흐름','자유간접화법','반복 모티프','1-12-1 대칭','23문장 아치','도시 몽타주','다중 시점','시간 교란','감각 전이','논리 반박'];
const kinds={project:'▣',character:'人',scene:'S',theme:'◇',question:'?',answer:'答',fact:'◆',motif:'≈',material:'物',location:'⌖',time:'⌚',situation:'!',technique:'✎'};
const defs={profile:['◉','Object Profile','현재 객체 핵심'],arc:['→','Story Arc','Scene 흐름'],scenes:['▦','Scene Cards','연결 장면'],situations:['!','Situations','개입 상황'],themes:['◇','Themes','주제 집계'],qa:['?','Questions / Answers','canonical Answer'],knowledge:['◆','Knowledge','Fact × Character'],motifs:['≈','Motif Flow','복선 수명주기'],manuscript:['✎','Related Manuscript','연결 원고'],relationships:['⌘','Relationship Map','연결 객체'],timeline:['⌚','Story Time','사건 시간'],voice:['◌','Voice Lab','POV 지문'],revision:['↻','Revision','수정 단계'],locations:['⌖','Locations','공간'],symbols:['✦','Symbols','사물·이미지']};
const templates={project:['profile','scenes','themes','qa','knowledge','motifs','relationships','timeline','locations','symbols','manuscript'],character:['profile','arc','scenes','situations','themes','qa','knowledge','motifs','relationships','voice','manuscript'],scene:['profile','scenes','situations','themes','knowledge','qa','motifs','relationships','locations','manuscript','revision'],theme:['profile','scenes','themes','qa','motifs','relationships','manuscript'],question:['profile','qa','themes','relationships','manuscript'],answer:['profile','qa','relationships','themes','scenes'],fact:['profile','scenes','knowledge','themes','motifs','relationships','manuscript'],motif:['profile','arc','scenes','situations','themes','motifs','relationships','locations','symbols','manuscript'],material:['profile','scenes','motifs','themes','relationships','locations','symbols','manuscript'],location:['profile','scenes','situations','relationships','motifs','themes','manuscript'],time:['profile','timeline','scenes','situations','relationships','manuscript'],situation:['profile','scenes','relationships','themes','motifs','knowledge','manuscript'],technique:['profile','scenes','relationships','themes','manuscript','revision']};
let seq=0;const objects=[];const add=(kind,title,glyph,summary,extra={})=>{const o={id:`${kind}-${++seq}`,kind,title,glyph:glyph||kinds[kind],meta:`${kind} · 철도 전망 호텔`,summary,relations:[],sceneRefs:[],themeRefs:[],...extra};objects.push(o);return o};
const project=add('project','철도 전망 호텔','▣','모든 Character·Scene·Theme·Question·Fact·Motif를 하나의 Object Card OS로 엮는 장편소설 프로젝트.',{id:'project-rail-hotel',relations:['유기오','최오윤','고통','철도 진동','Q1 고통은 존재하는가']});
characters.forEach((n,i)=>add('character',n,n==='유기오'?'유':n==='최오윤'?'최':n.slice(0,1),`${n}의 장면·상황·주제·질문·지식·모티프를 한 카드 페이지에서 모아봅니다.`,{id:n==='유기오'?'yukio':n==='최오윤'?'oyun':`character-${i}`,relations:n==='유기오'?['최오윤','미즈키','철도 진동','고통','인식']:n==='최오윤'?['유기오','고통','문손잡이']:[]}));
scenes.forEach((n,i)=>add('scene',`${String(i+1).padStart(2,'0')} ${n}`,String(i+1).padStart(2,'0'),`${n} 장면의 POV·상황·주제·모티프·Fact·대칭·원고를 카드로 관리합니다.`,{id:`scene-${String(i+1).padStart(2,'0')}`,relations:i===0?['유기오','철도 진동','종이컵','고통']:i===2?['유기오','철도 진동','인식','야마노테선']:[]}));
themes.forEach((n,i)=>add('theme',n,n==='고통'?'痛':'◇',`${n} 주제가 어떤 인물·장면·질문·Answer에서 어떻게 변하는지 모아봅니다.`,{id:n==='고통'?'pain':`theme-${i}`,relations:n==='고통'?['유기오','최오윤','Q1 고통은 존재하는가','철도 진동']:[]}));
add('question','Q1 고통은 존재하는가','?','동일한 질문에 대한 인물별 Answer를 비교하는 Question Object.',{id:'q1',relations:['유기오','최오윤','강아지 보리','고통']});
add('answer','Q1 × 유기오 Answer','答','질문과 인물을 연결하는 canonical Answer. 한 번 수정하면 모든 카드와 Matrix에 반영됩니다.',{relations:['유기오','Q1 고통은 존재하는가','고통']});
add('answer','Q1 × 최오윤 Answer','答','최오윤의 canonical Answer Object.',{relations:['최오윤','Q1 고통은 존재하는가','고통']});
add('fact','Fact 03 · 진동은 반복된다','◆','누가 이 사실을 알고 있는지 Scene별로 추적하는 Fact Object.',{id:'fact-03',relations:['유기오','최오윤','철도 진동']});
add('motif','철도 진동','≈','01 설치 → 03 반복 → 07 변형 → 12 회수로 이어지는 핵심 모티프.',{id:'vibration',relations:['유기오','고통','인식','철도 전망 호텔']});
materials.filter(x=>x!=='철도 진동').forEach((n,i)=>add('material',n,'物',`${n}이 등장한 장면과 상징 의미, 반복 수명주기를 모아봅니다.`,{id:`material-${i}`}));
locations.forEach((n,i)=>add('location',n,'⌖',`${n} 공간에 연결된 장면·인물·모티프를 모아봅니다.`,{id:`location-${i}`}));
times.forEach((n,i)=>add('time',n,'⌚',`${n} 시점의 사건과 원고 순서를 비교합니다.`,{id:`time-${i}`}));
situations.forEach((n,i)=>add('situation',n,'!',`${n} 상황이 발생한 장면과 개입 인물을 모아봅니다.`,{id:`situation-${i}`}));
techniques.forEach((n,i)=>add('technique',n,'✎',`${n} 기법이 사용된 Scene과 원고 예시를 모아봅니다.`,{id:`technique-${i}`}));
const byTitle=t=>objects.find(o=>o.title===t||o.title.replace(/^\d+\s+/,'')===t||o.title.includes(t));
const yukio=objects.find(o=>o.id==='yukio');yukio.sceneRefs=['01 호텔의 진동','03 야마노테선','07 지하 통로','10 병실 손잡이','11 폐쇄 승강장','12 다시 05:40'];yukio.themeRefs=['고통','인식','존재','미래'];
const oyun=objects.find(o=>o.id==='oyun');oyun.sceneRefs=['04 병원 복도','08 호텔 로비의 거짓말','10 병실 손잡이'];oyun.themeRefs=['고통','생존권리','미래'];
project.sceneRefs=scenes.map((n,i)=>`${String(i+1).padStart(2,'0')} ${n}`);project.themeRefs=themes;
const pain=objects.find(o=>o.id==='pain');pain.sceneRefs=['01 호텔의 진동','04 병원 복도','10 병실 손잡이'];pain.themeRefs=['인식','존재','생존권리'];
const vibration=objects.find(o=>o.id==='vibration');vibration.sceneRefs=['01 호텔의 진동','03 야마노테선','07 지하 통로','12 다시 05:40'];vibration.themeRefs=['인식','고통'];
const state={current:'project-rail-hotel',view:'object',mode:'cards',selected:null,palette:false,layouts:{}};
const saved=JSON.parse(localStorage.getItem('megaswing-preview-layouts')||'{}');state.layouts=saved;
function current(){return objects.find(o=>o.id===state.current)||project}function layout(){const o=current();return state.layouts[o.id]||(state.layouts[o.id]=[...(templates[o.kind]||templates.project)])}function save(){localStorage.setItem('megaswing-preview-layouts',JSON.stringify(state.layouts))}
function relationTargets(o){return [...new Set([...(o.relations||[]),...(o.sceneRefs||[]),...(o.themeRefs||[])])].map(byTitle).filter(Boolean).filter(x=>x.id!==o.id).slice(0,12)}
function body(key,o){if(key==='profile')return `<p class="summary">${o.summary}</p><div class="kv"><span>종류</span><b>${o.kind}</b></div><div class="kv"><span>원본</span><b>${o.title}</b></div>`;if(key==='arc')return `<div class="arc">${(o.sceneRefs.length?o.sceneRefs:['01 시작','03 전환','07 변형','12 회수']).map((x,i)=>`${i?'<span class="arrow">→</span>':''}<button class="arcnode" data-open-title="${x}">${x}</button>`).join('')}</div>`;if(key==='scenes')return o.sceneRefs.length?`<div class="scenes">${o.sceneRefs.map(x=>{const s=byTitle(x);return `<button class="scene" ${s?`data-open="${s.id}"`:''}><b>${x.slice(0,2)}</b><span>${x.replace(/^\d+\s+/,'')}</span></button>`}).join('')}</div>`:'<p class="empty">연결 Scene이 아직 없습니다.</p>';if(key==='situations')return `<div class="chips">${['진동 감지','기억 충돌','윤리 대화','부분 회수'].map(x=>`<span class="chip">${x}</span>`).join('')}</div>`;if(key==='themes')return `<div>${(o.themeRefs.length?o.themeRefs:['고통','인식','존재']).map((x,i)=>`<div class="barrow"><span>${x}</span><div class="track"><div class="fill" style="width:${Math.max(25,90-i*18)}%"></div></div><b>${Math.max(1,7-i)}</b></div>`).join('')}</div>`;if(key==='qa')return `<div class="qa"><b>Q1 · 고통은 존재하는가</b><p>${o.title.includes('최오윤')?'타인의 고통은 잘 모르겠으나 자신의 고통은 신체작용과 정신적 작용으로 존재한다고 본다.':'모른다. 하지만 인간 특유의 반응으로서 그것이 존재한다는 사실 자체는 자각 가능하다.'}</p></div>`;if(key==='knowledge')return `<div class="chips"><span class="chip hot">◆ 진동은 반복된다</span><span class="chip hot">◆ 문손잡이 기억</span><span class="chip">◇ 우산 소유자 모름</span></div>`;if(key==='motifs')return `<div class="chips"><span class="chip hot">설치</span><span class="chip hot">반복</span><span class="chip">변형</span><span class="chip">오인</span><span class="chip hot">회수</span></div>`;if(key==='relationships')return `<div class="chips">${relationTargets(o).map(x=>`<button class="chip" data-open="${x.id}">${x.glyph} ${x.title}</button>`).join('')||'<span class="empty">연결 Object가 아직 없습니다.</span>'}</div>`;if(key==='timeline')return `<div class="arc">${times.slice(0,6).map((x,i)=>`${i?'<span class="arrow">→</span>':''}<span class="arcnode">${x}</span>`).join('')}</div>`;if(key==='voice')return `<div class="chips"><span class="chip">평균문장 38자</span><span class="chip">질문문 8%</span><span class="chip">대화 31%</span><span class="chip">어휘다양도 .63</span></div>`;if(key==='revision')return `<div class="chips"><span class="chip hot">✓ 구조</span><span class="chip hot">✓ 인물</span><span class="chip">○ 주제·복선</span><span class="chip">○ 문장</span><span class="chip">○ 교정</span></div>`;if(key==='locations')return `<div class="chips">${locations.slice(0,5).map(x=>`<span class="chip">${x}</span>`).join('')}</div>`;if(key==='symbols')return `<div class="chips">${materials.slice(0,6).map(x=>`<span class="chip">${x}</span>`).join('')}</div>`;if(key==='manuscript')return `<p class="manuscript">열차 문이 닫힐 때마다 사람들의 몸이 같은 방향으로 기울었다. ${o.title}에 연결된 실제 원고는 canonical Scene 문서에서 모아 보여주는 구조입니다…</p>`;return ''}
function renderObjects(){const q=(document.getElementById('search').value||'').toLowerCase(),k=document.getElementById('kind').value;const list=objects.filter(o=>(k==='all'||o.kind===k)&&(!q||`${o.title} ${o.kind}`.toLowerCase().includes(q)));document.getElementById('objectCount').textContent=`${list.length} Objects`;document.getElementById('objectlist').innerHTML=list.map(o=>`<button class="nav ${state.view==='object'&&o.id===state.current?'active':''}" data-open="${o.id}"><span class="glyph">${o.glyph}</span><span class="navcopy"><b>${o.title}</b><small>${o.kind}</small></span></button>`).join('');bindOpen()}
function renderBlocks(){const o=current(),a=layout(),root=document.getElementById('blocks');root.className=`blocks ${state.mode==='cards'?'':state.mode}`;root.innerHTML=a.map((key,i)=>{const d=defs[key],wide=['arc','scenes','manuscript','relationships','timeline'].includes(key);return `<section class="block ${wide?'wide':''} ${state.selected===i?'selected':''}" data-index="${i}"><div class="toolbar"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-remove="${i}">×</button></div><div class="blockhead"><span class="blockicon">${d[0]}</span><div><b>${d[1]}</b><small>${d[2]}</small></div><span class="source">${o.kind.toUpperCase()}</span></div>${body(key,o)}</section>`}).join('');root.querySelectorAll('.block').forEach(x=>x.addEventListener('click',e=>{if(e.target.closest('button[data-open],button[data-open-title],.toolbar'))return;state.selected=Number(x.dataset.index);renderBlocks();renderInspector()}));root.querySelectorAll('[data-up]').forEach(x=>x.addEventListener('click',()=>move(+x.dataset.up,-1)));root.querySelectorAll('[data-down]').forEach(x=>x.addEventListener('click',()=>move(+x.dataset.down,1)));root.querySelectorAll('[data-remove]').forEach(x=>x.addEventListener('click',()=>{layout().splice(+x.dataset.remove,1);state.selected=null;save();render()}));bindOpen(root)}
function move(i,d){const a=layout(),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];state.selected=j;save();render()}
function renderPalette(){const a=layout();document.getElementById('palette').innerHTML=Object.entries(defs).map(([k,d])=>`<button data-add="${k}" ${a.includes(k)?'disabled':''}><b>${d[0]} ${d[1]}</b><span>${a.includes(k)?'이미 Object에 있음':d[2]}</span></button>`).join('');document.querySelectorAll('[data-add]').forEach(x=>x.addEventListener('click',()=>{layout().push(x.dataset.add);state.selected=layout().length-1;state.palette=false;save();render()}))}
function renderInspector(){const o=current(),box=document.getElementById('inspector');document.getElementById('inspectObject').textContent=o.title;document.getElementById('inspectKind').textContent=o.kind;if(state.view!=='object'||state.selected===null){box.innerHTML=`<p class="help">${state.view==='object'?'카드를 선택하세요.':'Visual Lens에서는 객체 관계를 탐색합니다.'}</p>`;return}const key=layout()[state.selected];box.innerHTML=`<div class="prop"><span>Block</span><b>${defs[key][1]}</b></div><div class="prop"><span>blockName</span><b>megaswing/${key}</b></div><div class="prop"><span>objectId</span><b>${o.id}</b></div><p class="help">실제 Gutenberg 구현에서는 이 배치 순서만 Preferences에 저장됩니다.</p>`}
function renderMap(){const o=current(),targets=relationTargets(o);return `<section class="lens"><div class="lenshead"><div><h2>Story Map</h2><p>현재 Object 주변의 Scene·Theme·Motif·관계 객체만 펼칩니다.</p></div><span class="badge">${targets.length} LINKS</span></div><div class="map"><div class="mapcenter"><b>${o.glyph} ${o.title}</b><small>${o.kind}</small></div>${targets.map(x=>`<button class="mapnode" data-open="${x.id}"><b>${x.glyph} ${x.title}</b><small>${x.kind}</small></button>`).join('')||'<p class="empty">연결 객체 없음</p>'}</div></section>`}
function renderTimeline(){const ss=objects.filter(o=>o.kind==='scene').sort((a,b)=>+a.glyph-+b.glyph);return `<section class="lens"><div class="lenshead"><div><h2>12 Scene Timeline</h2><p>장면 전체를 카드 흐름으로 보고 Scene Object로 바로 들어갑니다.</p></div><span class="badge">${ss.length} SCENES</span></div><div class="timeline">${ss.map(s=>`<button class="timecard" data-open="${s.id}"><strong>${s.glyph}</strong><b>${s.title.replace(/^\d+\s+/,'')}</b><small>${s.summary}</small></button>`).join('')}</div></section>`}
function renderMatrix(){const cs=objects.filter(o=>o.kind==='character').slice(0,10),ts=objects.filter(o=>o.kind==='theme').slice(0,10);return `<section class="lens"><div class="lenshead"><div><h2>10 Characters × 10 Themes</h2><p>행/열도 각각 원본 Object입니다. 클릭하면 그 카드 페이지로 이동합니다.</p></div><span class="badge">10 × 10</span></div><div class="matrixwrap"><table class="matrix"><thead><tr><th>Character</th>${ts.map(t=>`<th><button data-open="${t.id}">${t.title}</button></th>`).join('')}</tr></thead><tbody>${cs.map((c,ci)=>`<tr><td><button data-open="${c.id}">${c.title}</button></td>${ts.map((t,ti)=>{const hit=(c.id==='yukio'&&['고통','인식','존재','미래'].includes(t.title))||(c.id==='oyun'&&['고통','생존권리','미래'].includes(t.title))||((ci+ti)%7===0);return `<td><button class="${hit?'hit':''}" data-open="${c.id}" title="${c.title} × ${t.title}">${hit?Math.max(1,7-Math.abs(ci-ti)%5):'·'}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div></section>`}
function renderMain(){const o=current();document.getElementById('title').textContent=o.title;document.getElementById('avatar').textContent=o.glyph;document.getElementById('meta').textContent=o.meta;document.getElementById('crumb').textContent=`철도 전망 호텔 / ${state.view} / ${o.title}`;document.getElementById('badge').textContent=state.view==='object'?`${layout().length} BLOCKS`:state.view.toUpperCase();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const wrap=document.getElementById('workspace');if(state.view==='object'){wrap.innerHTML='<section class="canvas"><div id="blocks"></div></section><button class="add" id="addBlock">＋ Gutenberg Plugin Block 추가</button><div class="palette" id="palette"></div>';renderBlocks();renderPalette();document.getElementById('palette').classList.toggle('open',state.palette);document.getElementById('addBlock').addEventListener('click',()=>{state.palette=!state.palette;renderMain()})}else{wrap.innerHTML=state.view==='story-map'?renderMap():state.view==='timeline'?renderTimeline():renderMatrix();bindOpen(wrap)}renderInspector()}
function bindOpen(root=document){root.querySelectorAll('[data-open]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();state.current=x.dataset.open;state.view='object';state.selected=null;state.palette=false;render()}));root.querySelectorAll('[data-open-title]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();const o=byTitle(x.dataset.openTitle);if(o){state.current=o.id;state.view='object';state.selected=null;render()}}))}
function render(){renderObjects();renderMain()}
document.addEventListener('DOMContentLoaded',()=>{const kind=document.getElementById('kind');['all',...Object.keys(kinds)].forEach(k=>kind.insertAdjacentHTML('beforeend',`<option value="${k}">${k==='all'?`전체 객체 · ${objects.length}`:`${k} · ${objects.filter(o=>o.kind===k).length}`}</option>`));document.getElementById('search').addEventListener('input',renderObjects);kind.addEventListener('change',renderObjects);document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{state.view=x.dataset.view;state.selected=null;render()}));document.getElementById('projectBtn').addEventListener('click',()=>{state.current='project-rail-hotel';state.view='object';render()});document.getElementById('resetBtn').addEventListener('click',()=>{state.layouts[current().id]=[...(templates[current().kind]||templates.project)];save();render()});render()});