const KINDS={project:'▣',character:'人',scene:'S',theme:'◇',question:'?',answer:'答',fact:'◆',motif:'≈',material:'物',location:'⌖',time:'⌚',situation:'!',technique:'✎'};
const CHARACTERS=['유기오','최오윤','강아지 보리','미래인','영원의 신천지','아기','미즈키','사이비','외할머니','도시'];
const THEMES=['고통','abortion','미래','생존권리','영원','존재','인식','해결','카오스','코스모스'];
const SCENES=['호텔의 진동','붉은 우산','야마노테선','병원 복도','서점의 기억','강변의 미래인','지하 통로','호텔 로비의 거짓말','철도 건널목','병실 손잡이','폐쇄 승강장','다시 05:40'];
const TIMES=['05:40','07:10','08:30','10:00','11:45','13:00','15:20','17:30','22:00','02:30','23:40','05:40'];
const MATERIALS=['철도 진동','붉은 우산','종이컵','문손잡이','전광판','바흐 선율','층간소음','차가운 피부','젖은 종이','백색광'];
const SITUATIONS=['진동 감지','우산 오인','병실 회피','기억 충돌','미래 기억','윤리 대화','동물 시점','사이비 설교','도시 과부하','부분 회수'];
const STORAGE='megaswing-full-shell-v2';
const state={view:'dashboard',current:'project',query:'',kind:'all',saved:false,selectedCard:null};
const objects=[];
const add=(o)=>{objects.push(o);return o};
add({id:'project',kind:'project',title:'철도 전망 호텔',summary:'모든 인물·장면·주제·질문·Fact·모티프를 하나의 카드 OS에서 엮는 장편소설 프로젝트.',meta:'MegaSwing 360 · 12 Scenes · 10 Characters'});
CHARACTERS.forEach((name,i)=>add({id:i===0?'yukio':i===1?'oyun':`char-${i}`,kind:'character',title:name,summary:i===0?'세계를 이해하려 하지만 타인의 감각에 직접 접근할 수 없다는 결핍을 가진 중심 인물.':`${name}의 욕망·결핍·장면·상황·주제·지식을 한 카드에서 관리합니다.`,meta:`Character · ${i===0?'POV 9 · 12 Scenes':i===1?'POV 4 · 7 Scenes':'철도 전망 호텔'}`}));
SCENES.forEach((name,i)=>add({id:`scene-${String(i+1).padStart(2,'0')}`,kind:'scene',title:`${String(i+1).padStart(2,'0')} ${name}`,summary:`${name} 장면의 목적·인물·상황·주제·모티프·Fact·원고를 한 화면에서 관리합니다.`,meta:`Scene ${String(i+1).padStart(2,'0')} · ${TIMES[i]||''}`}));
THEMES.forEach((name,i)=>add({id:name==='고통'?'pain':`theme-${i}`,kind:'theme',title:name,summary:`${name} 주제가 어떤 인물·장면·질문·Answer를 통과하며 변하는지 추적합니다.`,meta:'Theme · 철도 전망 호텔'}));
add({id:'q1',kind:'question',title:'Q1 고통은 존재하는가',summary:'같은 질문에 대한 인물별 Answer를 비교하고 장면과 연결합니다.',meta:'Question · 고통'});
add({id:'fact-03',kind:'fact',title:'Fact 03 · 진동은 반복된다',summary:'누가 이 사실을 알고 있는지, 어느 장면에서 공개되는지 추적합니다.',meta:'Fact · Known by 유기오, 최오윤'});
add({id:'vibration',kind:'motif',title:'철도 진동',summary:'01 설치 → 03 반복 → 07 변형 → 12 회수로 이어지는 핵심 모티프.',meta:'Motif · 4 Scenes'});
MATERIALS.filter(x=>x!=='철도 진동').forEach((name,i)=>add({id:`material-${i}`,kind:'material',title:name,summary:`${name}의 상징 의미와 등장 장면을 관리합니다.`,meta:'Material'}));
SITUATIONS.forEach((name,i)=>add({id:`situation-${i}`,kind:'situation',title:name,summary:`${name} 상황이 어떤 인물과 장면에 영향을 주는지 관리합니다.`,meta:'Situation'}));

const defaultDrafts={
  yukio:{summary:'세계를 이해하려 하지만 타인의 감각에 직접 접근할 수 없다는 결핍을 가진 중심 인물.',desire:'세계의 구조를 이해한다.',lack:'타인의 감각에 직접 접근할 수 없다.',fear:'자신의 인식 자체가 오류일 가능성.',qa:'모른다. 하지만 어떤 것에 대한 인간 특유의 반응으로서 그것이 존재한다는 사실 자체는 자각 가능하다.',manuscript:'열차 문이 닫힐 때마다 사람들의 몸이 같은 방향으로 기울었다. 유기오는 손잡이를 쥔 채 전광판을 보았다. 초 단위가 바뀌는 순간 호텔의 종이컵에 생겼던 동심원이 떠올랐다.'},
  oyun:{summary:'본질보다 경험과 제거 가능성을 중시하는 인물.',desire:'주어진 조건 안에서 가능한 유희와 안정.',lack:'타인의 고통에 대한 확신.',fear:'통제 불가능한 고통.',qa:'타인의 고통은 잘 모르겠으나 자신의 고통은 기분과 관련된 신체작용과 정신적 작용으로 존재한다고 본다.',manuscript:'최오윤은 병원 복도의 백색광 아래서 문손잡이를 잡았다. 차가운 감촉이 기억보다 먼저 도착했다.'},
  'scene-03':{manuscript:'열차 문이 닫힐 때마다 사람들의 몸이 같은 방향으로 기울었다.\n\n유기오는 손잡이를 쥔 채 전광판을 보았다. 초 단위가 바뀌는 순간 호텔의 종이컵에 생겼던 동심원이 떠올랐다.\n\n사람들은 같은 방향으로 흔들렸지만, 같은 시간을 지나고 있는지는 알 수 없었다.',goal:'집단 리듬과 개인 감각의 대비를 통해 인식의 불확실성을 드러낸다.'}
};
let drafts=JSON.parse(localStorage.getItem(STORAGE)||'{}');
for(const [id,data] of Object.entries(defaultDrafts)) drafts[id]={...data,...(drafts[id]||{})};

const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const obj=()=>objects.find(o=>o.id===state.current)||objects[0];
const edit=(field,fallback='',multiline=false)=>`<${multiline?'div':'span'} class="editable ${multiline?'editable-block':''}" contenteditable="true" spellcheck="false" data-field="${field}">${esc((drafts[state.current]||{})[field]??fallback)}</${multiline?'div':'span'}>`;
function persist(){localStorage.setItem(STORAGE,JSON.stringify(drafts));const dot=$('#saveState');if(dot){dot.textContent='저장됨';dot.classList.add('is-saved');setTimeout(()=>dot.classList.remove('is-saved'),900)}}
function saveField(el){drafts[state.current]??={};drafts[state.current][el.dataset.field]=el.innerText.trim();persist();}
function openObject(id){if(!objects.find(o=>o.id===id))return;state.current=id;state.view='object';state.selectedCard=null;render();}
function byTitle(title){return objects.find(o=>o.title===title||o.title.replace(/^\d+\s+/,'')===title||o.title.includes(title));}
function sceneRefs(o){if(o.id==='yukio')return ['scene-01','scene-03','scene-07','scene-10','scene-11','scene-12'];if(o.id==='oyun')return ['scene-04','scene-08','scene-10'];if(o.id==='vibration')return ['scene-01','scene-03','scene-07','scene-12'];if(o.kind==='scene')return [o.id];if(o.kind==='project')return SCENES.map((_,i)=>`scene-${String(i+1).padStart(2,'0')}`);return ['scene-01','scene-03','scene-10'];}
function themeRefs(o){if(o.id==='yukio')return ['고통','인식','존재','미래'];if(o.id==='oyun')return ['고통','생존권리','미래'];if(o.id==='vibration')return ['인식','고통'];if(o.kind==='project')return THEMES;return ['고통','인식','존재'];}
function relationRefs(o){const fixed={yukio:['oyun','char-6','vibration','pain','q1'],'scene-03':['yukio','vibration','theme-6','q1'],'vibration':['yukio','pain','theme-6','scene-03'],pain:['yukio','oyun','q1','vibration']};return (fixed[o.id]||sceneRefs(o).slice(0,3)).map(id=>objects.find(x=>x.id===id)).filter(Boolean);}

function leftShell(){const kinds=['all',...new Set(objects.map(o=>o.kind))];const filtered=objects.filter(o=>(state.kind==='all'||o.kind===state.kind)&&(!state.query||`${o.title} ${o.kind}`.toLowerCase().includes(state.query.toLowerCase())));return `<aside class="leftbar"><div class="logoRow"><span class="logo">M</span><b>MegaSwing 360</b></div><button class="projectHome ${state.view==='dashboard'?'active':''}" data-view="dashboard">▣ 철도 전망 호텔</button><div class="sideLabel">WORKSPACE</div>${[['dashboard','⌂','대시보드'],['object','▦','Object Cards'],['manuscript','✎','원고'],['story-map','⌘','Story Map'],['timeline','≈','Timeline'],['matrix','▤','Matrix']].map(([v,g,t])=>`<button class="sideNav ${state.view===v?'active':''}" data-view="${v}"><span>${g}</span>${t}</button>`).join('')}<div class="sideLabel rowBetween"><span>OBJECTS</span><span>${filtered.length}</span></div><input id="objectSearch" class="sideInput" value="${esc(state.query)}" placeholder="객체 검색"><select id="kindFilter" class="sideInput">${kinds.map(k=>`<option value="${k}" ${state.kind===k?'selected':''}>${k==='all'?'전체 객체':k}</option>`).join('')}</select><div class="objectScroll">${filtered.map(o=>`<button class="objLink ${state.current===o.id&&state.view==='object'?'active':''}" data-open="${o.id}"><span class="objGlyph">${KINDS[o.kind]}</span><span><b>${esc(o.title)}</b><small>${o.kind}</small></span></button>`).join('')}</div></aside>`;}
function topbar(){return `<header class="topbar"><div class="breadcrumbs"><b>${state.view==='dashboard'?'프로젝트 홈':esc(obj().title)}</b><span> / ${state.view}</span></div><div class="topActions"><span id="saveState" class="saveState">자동저장</span><button id="quickWrite" class="primary">✎ 바로 쓰기</button><button id="resetEdits">↺ 편집 초기화</button></div></header>`;}
function inspector(){const o=obj();return `<aside class="rightbar"><div class="inspectorTitle">현재 선택</div><div class="inspectHero"><span>${KINDS[o.kind]}</span><div><b>${esc(o.title)}</b><small>${o.kind}</small></div></div><div class="inspectGroup"><label>Source</label><b>Canonical Object</b></div><div class="inspectGroup"><label>편집</label><p>보라색 점선이 보이는 텍스트를 클릭해 바로 수정합니다. 입력 후 포커스를 빼면 자동 저장됩니다.</p></div><div class="inspectGroup"><label>연결 객체</label><div class="miniChips">${relationRefs(o).map(x=>`<button data-open="${x.id}">${KINDS[x.kind]} ${esc(x.title)}</button>`).join('')}</div></div><div class="inspectGroup"><label>표시 원칙</label><p>객체의 원본은 하나만 유지하고 Scene·Theme·Q&A·Fact 카드는 같은 값을 다른 시점에서 보여줍니다.</p></div></aside>`;}
function dashboard(){return `<div class="dashboard"><section class="dashHero"><div><small>LONGFORM NOVEL OPERATING SYSTEM</small><h1>철도 전망 호텔</h1><p>${edit('projectSummary',objects[0].summary,true)}</p></div><button data-open="yukio" class="heroAction">오늘 유기오 계속 쓰기 →</button></section><div class="statGrid"><div><small>원고</small><b>42,680</b><span>/ 200,000자</span></div><div><small>Scene</small><b>12</b><span>/ 32장</span></div><div><small>Characters</small><b>10</b><span>연결됨</span></div><div><small>Motif</small><b>10</b><span>직조 중</span></div></div><div class="dashColumns"><section class="panel"><div class="panelHead"><b>오늘의 장면</b><button data-open="scene-03">전체보기</button></div><div class="focusScene"><span class="sceneNo">03</span><div><small>08:30 · 유기오 POV</small><h2>야마노테선</h2><p>${edit('todayGoal','집단 리듬과 개인 감각의 대비를 통해 인식의 불확실성을 드러낸다.',true)}</p></div></div><div class="quickManuscript" contenteditable="true" data-quick-field="manuscript" data-target="scene-03">${esc((drafts['scene-03']||{}).manuscript||'')}</div><div class="editorHint">클릭해서 바로 원고 편집 · 자동저장</div></section><section class="panel"><div class="panelHead"><b>인물</b><button data-open="yukio">Object 보기</button></div><div class="portraitGrid">${objects.filter(o=>o.kind==='character').slice(0,6).map(o=>`<button data-open="${o.id}"><span>${esc(o.title.slice(0,1))}</span><b>${esc(o.title)}</b><small>${o.id==='yukio'?'12 Scenes':o.id==='oyun'?'7 Scenes':'연결 보기'}</small></button>`).join('')}</div></section></div><section class="panel"><div class="panelHead"><b>장면 흐름</b><button data-view="timeline">Timeline</button></div><div class="sceneStrip">${SCENES.map((s,i)=>`<button data-open="scene-${String(i+1).padStart(2,'0')}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(s)}</span><small>${TIMES[i]}</small></button>`).join('')}</div></section></div>`;}
function card(title,icon,body,wide=false,key=''){return `<section class="card ${wide?'wide':''} ${state.selectedCard===key?'selected':''}" data-card="${key}"><header><span>${icon}</span><div><b>${title}</b><small>LIVE CARD</small></div><button class="cardMore">•••</button></header>${body}</section>`;}
function objectView(){const o=obj();const d=drafts[o.id]||{};const scenes=sceneRefs(o).map(id=>objects.find(x=>x.id===id)).filter(Boolean);const th=themeRefs(o);const profile=card('PROFILE','◉',`<p class="cardSummary">${edit('summary',d.summary||o.summary,true)}</p><div class="kvGrid"><label>욕망</label>${edit('desire',d.desire||'이 객체의 핵심 욕망/기능을 입력')}<label>결핍</label>${edit('lack',d.lack||'결핍 또는 구조적 한계를 입력')}<label>두려움</label>${edit('fear',d.fear||'두려움 또는 충돌 요소를 입력')}</div>`,false,'profile');const scenesCard=card('SCENE CARDS','▦',`<div class="sceneCards">${scenes.map(s=>`<button data-open="${s.id}"><b>${s.title.slice(0,2)}</b><span>${esc(s.title.replace(/^\d+\s+/,''))}</span><small>${esc(s.meta)}</small></button>`).join('')}</div>`,true,'scenes');const themesCard=card('THEMES','◇',`<div class="themeBars">${th.map((t,i)=>`<button data-open="${(byTitle(t)||{}).id||''}"><span>${esc(t)}</span><i><i style="width:${Math.max(24,92-i*16)}%"></i></i><b>${Math.max(2,7-i)}</b></button>`).join('')}</div>`,false,'themes');const qa=card('QUESTIONS / ANSWERS','?',`<button class="questionLink" data-open="q1">Q1 · 고통은 존재하는가 →</button>${edit('qa',d.qa||'이 인물의 답변을 바로 입력하세요.',true)}`,false,'qa');const knowledge=card('KNOWLEDGE','◆',`<div class="chips"><span class="known">◆ 진동은 반복된다</span><span class="known">◆ 문손잡이 기억</span><span>◇ 우산 소유자 모름</span><button>＋ Fact</button></div>`,false,'knowledge');const motif=card('MOTIF FLOW','≈',`<div class="motifFlow"><button data-open="vibration">철도 진동</button><span class="on">설치</span><span class="on">반복</span><span>변형</span><span>오인</span><span class="on">회수</span></div>`,true,'motif');const relation=card('RELATIONSHIPS','⌘',`<div class="relationGrid">${relationRefs(o).map(x=>`<button data-open="${x.id}"><span>${KINDS[x.kind]}</span><b>${esc(x.title)}</b><small>${x.kind}</small></button>`).join('')}</div>`,true,'relations');const manuscript=card('RELATED MANUSCRIPT','✎',`<div class="manuscriptEditor editable-block" contenteditable="true" spellcheck="false" data-field="manuscript">${esc(d.manuscript||'이 객체와 관련된 원고를 여기서 바로 쓰세요. 클릭하면 즉시 편집됩니다.')}</div><div class="editorFooter"><span>자동저장 · plain text preview</span><button data-view="manuscript">집필 화면으로 확대 ↗</button></div>`,true,'manuscript');return `<section class="objectHero"><div class="bigGlyph">${KINDS[o.kind]}</div><div><small>${o.kind.toUpperCase()} OBJECT</small><h1>${edit('title',o.title)}</h1><p>${esc(o.meta)}</p></div><div class="objectActions"><button data-view="story-map">⌘ 관계</button><button data-view="manuscript" class="primary">✎ 집필</button></div></section><div class="cardGrid">${profile}${themesCard}${scenesCard}${qa}${knowledge}${motif}${relation}${manuscript}</div><button class="addCard">＋ Gutenberg Plugin Block 추가</button>`;}
function manuscriptView(){const o=obj();const scenes=sceneRefs(o);const target=o.kind==='scene'?o.id:(scenes[0]||'scene-03');const t=objects.find(x=>x.id===target)||objects.find(x=>x.id==='scene-03');drafts[t.id]??={};return `<div class="writingShell"><div class="writingRail"><b>관련 장면</b>${scenes.map(id=>{const s=objects.find(x=>x.id===id);return s?`<button data-open="${s.id}" class="${s.id===t.id?'active':''}"><b>${s.title.slice(0,2)}</b><span>${esc(s.title.replace(/^\d+\s+/,''))}</span></button>`:''}).join('')}</div><article class="writingPaper"><div class="paperMeta">${esc(t.meta)} · 자동저장</div><h1 contenteditable="true" data-object-title="${t.id}">${esc(t.title.replace(/^\d+\s+/,''))}</h1><div class="paperBody" contenteditable="true" spellcheck="false" data-quick-field="manuscript" data-target="${t.id}">${esc((drafts[t.id]||{}).manuscript||'여기를 클릭해서 바로 원고를 쓰세요.')}</div></article><aside class="writingContext"><b>Scene Card</b><label>목적</label><div class="contextEdit" contenteditable="true" data-quick-field="goal" data-target="${t.id}">${esc((drafts[t.id]||{}).goal||'장면 목적 입력')}</div><label>주제</label><div class="miniChips"><span>고통</span><span>인식</span><span>존재</span></div><label>모티프</label><div class="miniChips"><span>철도 진동</span><span>전광판</span></div></aside></div>`;}
function storyMap(){const o=obj();const rel=relationRefs(o);return `<div class="lensHead"><div><small>VISUAL LENS</small><h1>${esc(o.title)} · Story Map</h1><p>현재 객체 주변의 인물·장면·주제·모티프만 펼칩니다.</p></div></div><div class="mapCanvas"><div class="centerNode"><span>${KINDS[o.kind]}</span><b>${esc(o.title)}</b><small>${o.kind}</small></div>${rel.map((x,i)=>`<button data-open="${x.id}" class="mapNode n${i+1}"><span>${KINDS[x.kind]}</span><b>${esc(x.title)}</b><small>${x.kind}</small></button>`).join('')}</div>`;}
function timeline(){return `<div class="lensHead"><div><small>12 SCENES</small><h1>Story Timeline</h1><p>원고 순서와 사건 시간을 한 줄에서 탐색합니다.</p></div></div><div class="timelineGrid">${SCENES.map((s,i)=>`<button data-open="scene-${String(i+1).padStart(2,'0')}"><span>${TIMES[i]}</span><b>${String(i+1).padStart(2,'0')} ${esc(s)}</b><small>${i<4?'초고':i<9?'구조':'회수'}</small></button>`).join('')}</div>`;}
function matrix(){return `<div class="lensHead"><div><small>10 × 10</small><h1>Characters × Themes</h1><p>인물별 주제 강도와 Answer 연결을 한 번에 봅니다.</p></div></div><div class="matrixWrap"><table><thead><tr><th>Character</th>${THEMES.map(t=>`<th>${esc(t)}</th>`).join('')}</tr></thead><tbody>${CHARACTERS.map((c,r)=>`<tr><th><button data-open="${objects.find(o=>o.title===c)?.id||''}">${esc(c)}</button></th>${THEMES.map((t,cx)=>{const v=(r*3+cx*5)%5;return `<td><button class="heat h${v}" data-open="${(byTitle(t)||{}).id||''}">${v?`${v}●`:''}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function mainContent(){if(state.view==='dashboard')return dashboard();if(state.view==='manuscript')return manuscriptView();if(state.view==='story-map')return storyMap();if(state.view==='timeline')return timeline();if(state.view==='matrix')return matrix();return objectView();}
function render(){document.getElementById('app').innerHTML=`${leftShell()}<div class="centerShell">${topbar()}<main class="content">${mainContent()}</main></div>${inspector()}`;bind();}
function bind(){
  $$('[data-open]').forEach(el=>el.onclick=e=>{e.stopPropagation();openObject(el.dataset.open)});
  $$('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render()});
  $('#objectSearch')?.addEventListener('input',e=>{state.query=e.target.value;render()});
  $('#kindFilter')?.addEventListener('change',e=>{state.kind=e.target.value;render()});
  $$('.editable').forEach(el=>{el.addEventListener('input',()=>{const s=$('#saveState');if(s)s.textContent='저장 중…'});el.addEventListener('blur',()=>saveField(el));});
  $$('[data-quick-field]').forEach(el=>{el.addEventListener('input',()=>{const s=$('#saveState');if(s)s.textContent='저장 중…';clearTimeout(el._timer);el._timer=setTimeout(()=>{drafts[el.dataset.target]??={};drafts[el.dataset.target][el.dataset.quickField]=el.innerText;persist()},350)});});
  $$('[data-object-title]').forEach(el=>el.addEventListener('blur',()=>{const target=objects.find(o=>o.id===el.dataset.objectTitle);if(target){const prefix=target.kind==='scene'?target.title.slice(0,3):'';target.title=prefix+el.innerText.trim();persist();render()}}));
  $$('.card').forEach(el=>el.onclick=e=>{if(e.target.closest('[contenteditable],button'))return;state.selectedCard=el.dataset.card;render()});
  $('#quickWrite')?.addEventListener('click',()=>{state.current=state.current==='project'?'scene-03':state.current;state.view='manuscript';render()});
  $('#resetEdits')?.addEventListener('click',()=>{if(confirm('현재 브라우저의 편집 내용을 초기화할까요?')){localStorage.removeItem(STORAGE);location.reload()}});
}
render();